//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantillaCarrusel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SistemaMatriculaEntities : DbContext
    {
        public SistemaMatriculaEntities()
            : base("name=SistemaMatriculaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumnoes { get; set; }
        public virtual DbSet<Canton> Cantons { get; set; }
        public virtual DbSet<Carrera> Carreras { get; set; }
        public virtual DbSet<Distrito> Distritoes { get; set; }
        public virtual DbSet<EnvioCorreo> EnvioCorreos { get; set; }
        public virtual DbSet<Grado> Grados { get; set; }
        public virtual DbSet<Materia> Materias { get; set; }
        public virtual DbSet<Matricula> Matriculas { get; set; }
        public virtual DbSet<Periodo> Periodos { get; set; }
        public virtual DbSet<Provincia> Provincias { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    
        public virtual ObjectResult<RetornaCantones_Result> RetornaCantones(string nombre, Nullable<int> id_Provincia)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var id_ProvinciaParameter = id_Provincia.HasValue ?
                new ObjectParameter("id_Provincia", id_Provincia) :
                new ObjectParameter("id_Provincia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaCantones_Result>("RetornaCantones", nombreParameter, id_ProvinciaParameter);
        }
    
        public virtual ObjectResult<RetornaCantonesID_Result> RetornaCantonesID(Nullable<int> id_Canton)
        {
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("id_Canton", id_Canton) :
                new ObjectParameter("id_Canton", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaCantonesID_Result>("RetornaCantonesID", id_CantonParameter);
        }
    
        public virtual ObjectResult<RetornaProvincias_Result> RetornaProvincias()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaProvincias_Result>("RetornaProvincias");
        }
    
        public virtual int sp_ActualizaAlumno(Nullable<int> id_Alumno, Nullable<System.DateTime> fecha_Ingreso, string cedula, string genero, Nullable<System.DateTime> fecha_Nacimiento, string nombre, string apellido1, string apellido2, string direccion, string telefono1, string telefono2, string correo, Nullable<int> id_Provincia, Nullable<int> id_Canton, Nullable<int> id_Distrito)
        {
            var id_AlumnoParameter = id_Alumno.HasValue ?
                new ObjectParameter("id_Alumno", id_Alumno) :
                new ObjectParameter("id_Alumno", typeof(int));
    
            var fecha_IngresoParameter = fecha_Ingreso.HasValue ?
                new ObjectParameter("Fecha_Ingreso", fecha_Ingreso) :
                new ObjectParameter("Fecha_Ingreso", typeof(System.DateTime));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var generoParameter = genero != null ?
                new ObjectParameter("Genero", genero) :
                new ObjectParameter("Genero", typeof(string));
    
            var fecha_NacimientoParameter = fecha_Nacimiento.HasValue ?
                new ObjectParameter("Fecha_Nacimiento", fecha_Nacimiento) :
                new ObjectParameter("Fecha_Nacimiento", typeof(System.DateTime));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("Apellido1", apellido1) :
                new ObjectParameter("Apellido1", typeof(string));
    
            var apellido2Parameter = apellido2 != null ?
                new ObjectParameter("Apellido2", apellido2) :
                new ObjectParameter("Apellido2", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var telefono1Parameter = telefono1 != null ?
                new ObjectParameter("Telefono1", telefono1) :
                new ObjectParameter("Telefono1", typeof(string));
    
            var telefono2Parameter = telefono2 != null ?
                new ObjectParameter("Telefono2", telefono2) :
                new ObjectParameter("Telefono2", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var id_ProvinciaParameter = id_Provincia.HasValue ?
                new ObjectParameter("id_Provincia", id_Provincia) :
                new ObjectParameter("id_Provincia", typeof(int));
    
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("id_Canton", id_Canton) :
                new ObjectParameter("id_Canton", typeof(int));
    
            var id_DistritoParameter = id_Distrito.HasValue ?
                new ObjectParameter("id_Distrito", id_Distrito) :
                new ObjectParameter("id_Distrito", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizaAlumno", id_AlumnoParameter, fecha_IngresoParameter, cedulaParameter, generoParameter, fecha_NacimientoParameter, nombreParameter, apellido1Parameter, apellido2Parameter, direccionParameter, telefono1Parameter, telefono2Parameter, correoParameter, id_ProvinciaParameter, id_CantonParameter, id_DistritoParameter);
        }
    
        public virtual int sp_ActualizaCarrera(Nullable<int> id_Carrera, Nullable<int> id_Grado, string nombre, string descripcion)
        {
            var id_CarreraParameter = id_Carrera.HasValue ?
                new ObjectParameter("id_Carrera", id_Carrera) :
                new ObjectParameter("id_Carrera", typeof(int));
    
            var id_GradoParameter = id_Grado.HasValue ?
                new ObjectParameter("id_Grado", id_Grado) :
                new ObjectParameter("id_Grado", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizaCarrera", id_CarreraParameter, id_GradoParameter, nombreParameter, descripcionParameter);
        }
    
        public virtual int sp_ActualizaCorreo(Nullable<int> id_Envio, string estado, string bitacora)
        {
            var id_EnvioParameter = id_Envio.HasValue ?
                new ObjectParameter("id_Envio", id_Envio) :
                new ObjectParameter("id_Envio", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            var bitacoraParameter = bitacora != null ?
                new ObjectParameter("Bitacora", bitacora) :
                new ObjectParameter("Bitacora", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizaCorreo", id_EnvioParameter, estadoParameter, bitacoraParameter);
        }
    
        public virtual int sp_ActualizaGrados(Nullable<int> id_Grado, string nombre, string descripcion)
        {
            var id_GradoParameter = id_Grado.HasValue ?
                new ObjectParameter("id_Grado", id_Grado) :
                new ObjectParameter("id_Grado", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizaGrados", id_GradoParameter, nombreParameter, descripcionParameter);
        }
    
        public virtual int sp_ActualizaMateria(Nullable<int> id_Materia, string nombre, string codigo, Nullable<int> cant_Creditos, Nullable<int> cant_Horas)
        {
            var id_MateriaParameter = id_Materia.HasValue ?
                new ObjectParameter("id_Materia", id_Materia) :
                new ObjectParameter("id_Materia", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var cant_CreditosParameter = cant_Creditos.HasValue ?
                new ObjectParameter("Cant_Creditos", cant_Creditos) :
                new ObjectParameter("Cant_Creditos", typeof(int));
    
            var cant_HorasParameter = cant_Horas.HasValue ?
                new ObjectParameter("Cant_Horas", cant_Horas) :
                new ObjectParameter("Cant_Horas", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizaMateria", id_MateriaParameter, nombreParameter, codigoParameter, cant_CreditosParameter, cant_HorasParameter);
        }
    
        public virtual int sp_ActualizaMateriaCarrera(Nullable<int> id_CarreraOLD, Nullable<int> id_MateriaOLD, Nullable<int> id_CarreraNEW, Nullable<int> id_MateriaNEW)
        {
            var id_CarreraOLDParameter = id_CarreraOLD.HasValue ?
                new ObjectParameter("id_CarreraOLD", id_CarreraOLD) :
                new ObjectParameter("id_CarreraOLD", typeof(int));
    
            var id_MateriaOLDParameter = id_MateriaOLD.HasValue ?
                new ObjectParameter("id_MateriaOLD", id_MateriaOLD) :
                new ObjectParameter("id_MateriaOLD", typeof(int));
    
            var id_CarreraNEWParameter = id_CarreraNEW.HasValue ?
                new ObjectParameter("id_CarreraNEW", id_CarreraNEW) :
                new ObjectParameter("id_CarreraNEW", typeof(int));
    
            var id_MateriaNEWParameter = id_MateriaNEW.HasValue ?
                new ObjectParameter("id_MateriaNEW", id_MateriaNEW) :
                new ObjectParameter("id_MateriaNEW", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizaMateriaCarrera", id_CarreraOLDParameter, id_MateriaOLDParameter, id_CarreraNEWParameter, id_MateriaNEWParameter);
        }
    
        public virtual int sp_ActualizaMatricula(Nullable<int> id_Matricula, Nullable<int> id_Materia, Nullable<int> id_Alumno, Nullable<int> nota, Nullable<int> id_Periodo)
        {
            var id_MatriculaParameter = id_Matricula.HasValue ?
                new ObjectParameter("id_Matricula", id_Matricula) :
                new ObjectParameter("id_Matricula", typeof(int));
    
            var id_MateriaParameter = id_Materia.HasValue ?
                new ObjectParameter("id_Materia", id_Materia) :
                new ObjectParameter("id_Materia", typeof(int));
    
            var id_AlumnoParameter = id_Alumno.HasValue ?
                new ObjectParameter("id_Alumno", id_Alumno) :
                new ObjectParameter("id_Alumno", typeof(int));
    
            var notaParameter = nota.HasValue ?
                new ObjectParameter("Nota", nota) :
                new ObjectParameter("Nota", typeof(int));
    
            var id_PeriodoParameter = id_Periodo.HasValue ?
                new ObjectParameter("id_Periodo", id_Periodo) :
                new ObjectParameter("id_Periodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizaMatricula", id_MatriculaParameter, id_MateriaParameter, id_AlumnoParameter, notaParameter, id_PeriodoParameter);
        }
    
        public virtual int sp_ActualizaPeriodo(Nullable<int> id_Periodo, string codigo, Nullable<System.DateTime> fecha_Inicio, Nullable<System.DateTime> fecha_Fin)
        {
            var id_PeriodoParameter = id_Periodo.HasValue ?
                new ObjectParameter("id_Periodo", id_Periodo) :
                new ObjectParameter("id_Periodo", typeof(int));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var fecha_InicioParameter = fecha_Inicio.HasValue ?
                new ObjectParameter("Fecha_Inicio", fecha_Inicio) :
                new ObjectParameter("Fecha_Inicio", typeof(System.DateTime));
    
            var fecha_FinParameter = fecha_Fin.HasValue ?
                new ObjectParameter("Fecha_Fin", fecha_Fin) :
                new ObjectParameter("Fecha_Fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizaPeriodo", id_PeriodoParameter, codigoParameter, fecha_InicioParameter, fecha_FinParameter);
        }
    
        public virtual int sp_ActualizaUsuario(Nullable<int> id_Usuario, Nullable<int> id_Alumno, string usuario, string contrasena, Nullable<System.DateTime> ultimaAccion, Nullable<bool> activo, Nullable<bool> esAlumno)
        {
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("id_Usuario", id_Usuario) :
                new ObjectParameter("id_Usuario", typeof(int));
    
            var id_AlumnoParameter = id_Alumno.HasValue ?
                new ObjectParameter("id_Alumno", id_Alumno) :
                new ObjectParameter("id_Alumno", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            var ultimaAccionParameter = ultimaAccion.HasValue ?
                new ObjectParameter("UltimaAccion", ultimaAccion) :
                new ObjectParameter("UltimaAccion", typeof(System.DateTime));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            var esAlumnoParameter = esAlumno.HasValue ?
                new ObjectParameter("EsAlumno", esAlumno) :
                new ObjectParameter("EsAlumno", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizaUsuario", id_UsuarioParameter, id_AlumnoParameter, usuarioParameter, contrasenaParameter, ultimaAccionParameter, activoParameter, esAlumnoParameter);
        }
    
        public virtual int sp_EliminaAlumno(Nullable<int> id_Alumno)
        {
            var id_AlumnoParameter = id_Alumno.HasValue ?
                new ObjectParameter("id_Alumno", id_Alumno) :
                new ObjectParameter("id_Alumno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaAlumno", id_AlumnoParameter);
        }
    
        public virtual int sp_EliminaCanton(Nullable<int> id_Canton)
        {
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("id_Canton", id_Canton) :
                new ObjectParameter("id_Canton", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaCanton", id_CantonParameter);
        }
    
        public virtual int sp_EliminaCarrera(Nullable<int> id_Carrera, Nullable<int> id_Grado)
        {
            var id_CarreraParameter = id_Carrera.HasValue ?
                new ObjectParameter("id_Carrera", id_Carrera) :
                new ObjectParameter("id_Carrera", typeof(int));
    
            var id_GradoParameter = id_Grado.HasValue ?
                new ObjectParameter("id_Grado", id_Grado) :
                new ObjectParameter("id_Grado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaCarrera", id_CarreraParameter, id_GradoParameter);
        }
    
        public virtual int sp_EliminaGrados(Nullable<int> id_Grado)
        {
            var id_GradoParameter = id_Grado.HasValue ?
                new ObjectParameter("id_Grado", id_Grado) :
                new ObjectParameter("id_Grado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaGrados", id_GradoParameter);
        }
    
        public virtual int sp_EliminaMateria(Nullable<int> id_Materia)
        {
            var id_MateriaParameter = id_Materia.HasValue ?
                new ObjectParameter("id_Materia", id_Materia) :
                new ObjectParameter("id_Materia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaMateria", id_MateriaParameter);
        }
    
        public virtual int sp_EliminaMateriaCarrera(Nullable<int> id_Carrera, Nullable<int> id_Materia)
        {
            var id_CarreraParameter = id_Carrera.HasValue ?
                new ObjectParameter("id_Carrera", id_Carrera) :
                new ObjectParameter("id_Carrera", typeof(int));
    
            var id_MateriaParameter = id_Materia.HasValue ?
                new ObjectParameter("id_Materia", id_Materia) :
                new ObjectParameter("id_Materia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaMateriaCarrera", id_CarreraParameter, id_MateriaParameter);
        }
    
        public virtual int sp_EliminaMatricula(Nullable<int> id_Matricula)
        {
            var id_MatriculaParameter = id_Matricula.HasValue ?
                new ObjectParameter("id_Matricula", id_Matricula) :
                new ObjectParameter("id_Matricula", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaMatricula", id_MatriculaParameter);
        }
    
        public virtual int sp_EliminaPeriodo(Nullable<int> id_Periodo)
        {
            var id_PeriodoParameter = id_Periodo.HasValue ?
                new ObjectParameter("id_Periodo", id_Periodo) :
                new ObjectParameter("id_Periodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaPeriodo", id_PeriodoParameter);
        }
    
        public virtual int sp_EliminaUsuario(Nullable<int> id_Usuario)
        {
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("id_Usuario", id_Usuario) :
                new ObjectParameter("id_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaUsuario", id_UsuarioParameter);
        }
    
        public virtual int sp_InsertaAlumno(Nullable<System.DateTime> fecha_Ingreso, string cedula, string genero, Nullable<System.DateTime> fecha_Nacimiento, string nombre, string apellido1, string apellido2, string direccion, string telefono1, string telefono2, string correo, Nullable<int> id_Provincia, Nullable<int> id_Canton, Nullable<int> id_Distrito)
        {
            var fecha_IngresoParameter = fecha_Ingreso.HasValue ?
                new ObjectParameter("Fecha_Ingreso", fecha_Ingreso) :
                new ObjectParameter("Fecha_Ingreso", typeof(System.DateTime));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var generoParameter = genero != null ?
                new ObjectParameter("Genero", genero) :
                new ObjectParameter("Genero", typeof(string));
    
            var fecha_NacimientoParameter = fecha_Nacimiento.HasValue ?
                new ObjectParameter("Fecha_Nacimiento", fecha_Nacimiento) :
                new ObjectParameter("Fecha_Nacimiento", typeof(System.DateTime));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("Apellido1", apellido1) :
                new ObjectParameter("Apellido1", typeof(string));
    
            var apellido2Parameter = apellido2 != null ?
                new ObjectParameter("Apellido2", apellido2) :
                new ObjectParameter("Apellido2", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var telefono1Parameter = telefono1 != null ?
                new ObjectParameter("Telefono1", telefono1) :
                new ObjectParameter("Telefono1", typeof(string));
    
            var telefono2Parameter = telefono2 != null ?
                new ObjectParameter("Telefono2", telefono2) :
                new ObjectParameter("Telefono2", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var id_ProvinciaParameter = id_Provincia.HasValue ?
                new ObjectParameter("id_Provincia", id_Provincia) :
                new ObjectParameter("id_Provincia", typeof(int));
    
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("id_Canton", id_Canton) :
                new ObjectParameter("id_Canton", typeof(int));
    
            var id_DistritoParameter = id_Distrito.HasValue ?
                new ObjectParameter("id_Distrito", id_Distrito) :
                new ObjectParameter("id_Distrito", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaAlumno", fecha_IngresoParameter, cedulaParameter, generoParameter, fecha_NacimientoParameter, nombreParameter, apellido1Parameter, apellido2Parameter, direccionParameter, telefono1Parameter, telefono2Parameter, correoParameter, id_ProvinciaParameter, id_CantonParameter, id_DistritoParameter);
        }
    
        public virtual int sp_InsertaCanton(Nullable<int> id_Provincia, string nombre, Nullable<int> id_CantonInec)
        {
            var id_ProvinciaParameter = id_Provincia.HasValue ?
                new ObjectParameter("id_Provincia", id_Provincia) :
                new ObjectParameter("id_Provincia", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var id_CantonInecParameter = id_CantonInec.HasValue ?
                new ObjectParameter("id_CantonInec", id_CantonInec) :
                new ObjectParameter("id_CantonInec", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaCanton", id_ProvinciaParameter, nombreParameter, id_CantonInecParameter);
        }
    
        public virtual int sp_InsertaCarrera(Nullable<int> id_Grado, string nombre, string descripcion)
        {
            var id_GradoParameter = id_Grado.HasValue ?
                new ObjectParameter("id_Grado", id_Grado) :
                new ObjectParameter("id_Grado", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaCarrera", id_GradoParameter, nombreParameter, descripcionParameter);
        }
    
        public virtual int sp_InsertaCorreo(string destinatario, string asunto, string cuerpo, string estado, string bitacora)
        {
            var destinatarioParameter = destinatario != null ?
                new ObjectParameter("Destinatario", destinatario) :
                new ObjectParameter("Destinatario", typeof(string));
    
            var asuntoParameter = asunto != null ?
                new ObjectParameter("Asunto", asunto) :
                new ObjectParameter("Asunto", typeof(string));
    
            var cuerpoParameter = cuerpo != null ?
                new ObjectParameter("Cuerpo", cuerpo) :
                new ObjectParameter("Cuerpo", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            var bitacoraParameter = bitacora != null ?
                new ObjectParameter("Bitacora", bitacora) :
                new ObjectParameter("Bitacora", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaCorreo", destinatarioParameter, asuntoParameter, cuerpoParameter, estadoParameter, bitacoraParameter);
        }
    
        public virtual int sp_InsertaGrados(string nombre, string descripcion)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaGrados", nombreParameter, descripcionParameter);
        }
    
        public virtual int sp_InsertaMateria(string nombre, string codigo, Nullable<int> cant_Creditos, Nullable<int> cant_Horas)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var cant_CreditosParameter = cant_Creditos.HasValue ?
                new ObjectParameter("Cant_Creditos", cant_Creditos) :
                new ObjectParameter("Cant_Creditos", typeof(int));
    
            var cant_HorasParameter = cant_Horas.HasValue ?
                new ObjectParameter("Cant_Horas", cant_Horas) :
                new ObjectParameter("Cant_Horas", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaMateria", nombreParameter, codigoParameter, cant_CreditosParameter, cant_HorasParameter);
        }
    
        public virtual int sp_InsertaMateriaCarrera(Nullable<int> id_Carrera, Nullable<int> id_Materia)
        {
            var id_CarreraParameter = id_Carrera.HasValue ?
                new ObjectParameter("id_Carrera", id_Carrera) :
                new ObjectParameter("id_Carrera", typeof(int));
    
            var id_MateriaParameter = id_Materia.HasValue ?
                new ObjectParameter("id_Materia", id_Materia) :
                new ObjectParameter("id_Materia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaMateriaCarrera", id_CarreraParameter, id_MateriaParameter);
        }
    
        public virtual int sp_InsertaMatricula(Nullable<int> id_Materia, Nullable<int> id_Alumno, Nullable<int> nota, Nullable<int> id_Periodo)
        {
            var id_MateriaParameter = id_Materia.HasValue ?
                new ObjectParameter("id_Materia", id_Materia) :
                new ObjectParameter("id_Materia", typeof(int));
    
            var id_AlumnoParameter = id_Alumno.HasValue ?
                new ObjectParameter("id_Alumno", id_Alumno) :
                new ObjectParameter("id_Alumno", typeof(int));
    
            var notaParameter = nota.HasValue ?
                new ObjectParameter("Nota", nota) :
                new ObjectParameter("Nota", typeof(int));
    
            var id_PeriodoParameter = id_Periodo.HasValue ?
                new ObjectParameter("id_Periodo", id_Periodo) :
                new ObjectParameter("id_Periodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaMatricula", id_MateriaParameter, id_AlumnoParameter, notaParameter, id_PeriodoParameter);
        }
    
        public virtual int sp_InsertaPeriodo(string codigo, Nullable<System.DateTime> fecha_Inicio, Nullable<System.DateTime> fecha_Fin)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var fecha_InicioParameter = fecha_Inicio.HasValue ?
                new ObjectParameter("Fecha_Inicio", fecha_Inicio) :
                new ObjectParameter("Fecha_Inicio", typeof(System.DateTime));
    
            var fecha_FinParameter = fecha_Fin.HasValue ?
                new ObjectParameter("Fecha_Fin", fecha_Fin) :
                new ObjectParameter("Fecha_Fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaPeriodo", codigoParameter, fecha_InicioParameter, fecha_FinParameter);
        }
    
        public virtual int sp_InsertaUsuario(Nullable<int> id_Alumno, string usuario, string contrasena, Nullable<System.DateTime> ultimaAccion, Nullable<bool> activo, Nullable<bool> esAlumno)
        {
            var id_AlumnoParameter = id_Alumno.HasValue ?
                new ObjectParameter("id_Alumno", id_Alumno) :
                new ObjectParameter("id_Alumno", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            var ultimaAccionParameter = ultimaAccion.HasValue ?
                new ObjectParameter("UltimaAccion", ultimaAccion) :
                new ObjectParameter("UltimaAccion", typeof(System.DateTime));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            var esAlumnoParameter = esAlumno.HasValue ?
                new ObjectParameter("EsAlumno", esAlumno) :
                new ObjectParameter("EsAlumno", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaUsuario", id_AlumnoParameter, usuarioParameter, contrasenaParameter, ultimaAccionParameter, activoParameter, esAlumnoParameter);
        }
    
        public virtual int sp_ModificaCanton(Nullable<int> id_Canton, Nullable<int> id_Provincia, string nombre, Nullable<int> id_CantonInec)
        {
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("id_Canton", id_Canton) :
                new ObjectParameter("id_Canton", typeof(int));
    
            var id_ProvinciaParameter = id_Provincia.HasValue ?
                new ObjectParameter("id_Provincia", id_Provincia) :
                new ObjectParameter("id_Provincia", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var id_CantonInecParameter = id_CantonInec.HasValue ?
                new ObjectParameter("id_CantonInec", id_CantonInec) :
                new ObjectParameter("id_CantonInec", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaCanton", id_CantonParameter, id_ProvinciaParameter, nombreParameter, id_CantonInecParameter);
        }
    
        public virtual int sp_ReprocesaCorreosError()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ReprocesaCorreosError");
        }
    
        public virtual ObjectResult<sp_RetornaAlumno_Result> sp_RetornaAlumno()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaAlumno_Result>("sp_RetornaAlumno");
        }
    
        public virtual ObjectResult<sp_RetornaAlumnoporID_Result> sp_RetornaAlumnoporID(Nullable<int> id_Alumno)
        {
            var id_AlumnoParameter = id_Alumno.HasValue ?
                new ObjectParameter("id_Alumno", id_Alumno) :
                new ObjectParameter("id_Alumno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaAlumnoporID_Result>("sp_RetornaAlumnoporID", id_AlumnoParameter);
        }
    
        public virtual ObjectResult<sp_RetornaCarrera_Result> sp_RetornaCarrera()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaCarrera_Result>("sp_RetornaCarrera");
        }
    
        public virtual ObjectResult<sp_RetornaCarreraPorID_Result> sp_RetornaCarreraPorID(Nullable<int> id_Carrera, Nullable<int> id_Grado)
        {
            var id_CarreraParameter = id_Carrera.HasValue ?
                new ObjectParameter("id_Carrera", id_Carrera) :
                new ObjectParameter("id_Carrera", typeof(int));
    
            var id_GradoParameter = id_Grado.HasValue ?
                new ObjectParameter("id_Grado", id_Grado) :
                new ObjectParameter("id_Grado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaCarreraPorID_Result>("sp_RetornaCarreraPorID", id_CarreraParameter, id_GradoParameter);
        }
    
        public virtual ObjectResult<sp_RetornaCorreosPendientes_Result> sp_RetornaCorreosPendientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaCorreosPendientes_Result>("sp_RetornaCorreosPendientes");
        }
    
        public virtual ObjectResult<sp_RetornaGrados_Result> sp_RetornaGrados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaGrados_Result>("sp_RetornaGrados");
        }
    
        public virtual ObjectResult<sp_RetornaGradosPorID_Result> sp_RetornaGradosPorID(Nullable<int> id_Grado)
        {
            var id_GradoParameter = id_Grado.HasValue ?
                new ObjectParameter("id_Grado", id_Grado) :
                new ObjectParameter("id_Grado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaGradosPorID_Result>("sp_RetornaGradosPorID", id_GradoParameter);
        }
    
        public virtual ObjectResult<sp_RetornaInicioSesion_Result> sp_RetornaInicioSesion(string usuario, string contrasena)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaInicioSesion_Result>("sp_RetornaInicioSesion", usuarioParameter, contrasenaParameter);
        }
    
        public virtual ObjectResult<sp_RetornaMateria_Result> sp_RetornaMateria()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaMateria_Result>("sp_RetornaMateria");
        }
    
        public virtual ObjectResult<sp_RetornaMateriaPorID_Result> sp_RetornaMateriaPorID(Nullable<int> id_Materia)
        {
            var id_MateriaParameter = id_Materia.HasValue ?
                new ObjectParameter("id_Materia", id_Materia) :
                new ObjectParameter("id_Materia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaMateriaPorID_Result>("sp_RetornaMateriaPorID", id_MateriaParameter);
        }
    
        public virtual ObjectResult<sp_RetornaMateriasAlumnoporID_Result> sp_RetornaMateriasAlumnoporID(Nullable<int> id_Alumno)
        {
            var id_AlumnoParameter = id_Alumno.HasValue ?
                new ObjectParameter("id_Alumno", id_Alumno) :
                new ObjectParameter("id_Alumno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaMateriasAlumnoporID_Result>("sp_RetornaMateriasAlumnoporID", id_AlumnoParameter);
        }
    
        public virtual ObjectResult<sp_RetornaMateriasCarrera_Result> sp_RetornaMateriasCarrera()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaMateriasCarrera_Result>("sp_RetornaMateriasCarrera");
        }
    
        public virtual ObjectResult<sp_RetornaMateriasCarreraPorCarrera_Result> sp_RetornaMateriasCarreraPorCarrera(Nullable<int> id_Materia)
        {
            var id_MateriaParameter = id_Materia.HasValue ?
                new ObjectParameter("id_Materia", id_Materia) :
                new ObjectParameter("id_Materia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaMateriasCarreraPorCarrera_Result>("sp_RetornaMateriasCarreraPorCarrera", id_MateriaParameter);
        }
    
        public virtual ObjectResult<sp_RetornaMateriasCarreraPorMateria_Result> sp_RetornaMateriasCarreraPorMateria(Nullable<int> id_Carrera)
        {
            var id_CarreraParameter = id_Carrera.HasValue ?
                new ObjectParameter("id_Carrera", id_Carrera) :
                new ObjectParameter("id_Carrera", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaMateriasCarreraPorMateria_Result>("sp_RetornaMateriasCarreraPorMateria", id_CarreraParameter);
        }
    
        public virtual ObjectResult<sp_RetornaMateriasPeriodoporID_Result> sp_RetornaMateriasPeriodoporID(Nullable<int> id_Periodo)
        {
            var id_PeriodoParameter = id_Periodo.HasValue ?
                new ObjectParameter("id_Periodo", id_Periodo) :
                new ObjectParameter("id_Periodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaMateriasPeriodoporID_Result>("sp_RetornaMateriasPeriodoporID", id_PeriodoParameter);
        }
    
        public virtual ObjectResult<sp_RetornaMatricula_Result> sp_RetornaMatricula()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaMatricula_Result>("sp_RetornaMatricula");
        }
    
        public virtual ObjectResult<sp_RetornaMatriculaporAlumno_Result> sp_RetornaMatriculaporAlumno(Nullable<int> id_Alumno)
        {
            var id_AlumnoParameter = id_Alumno.HasValue ?
                new ObjectParameter("id_Alumno", id_Alumno) :
                new ObjectParameter("id_Alumno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaMatriculaporAlumno_Result>("sp_RetornaMatriculaporAlumno", id_AlumnoParameter);
        }
    
        public virtual ObjectResult<sp_RetornaPeriodo_Result> sp_RetornaPeriodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaPeriodo_Result>("sp_RetornaPeriodo");
        }
    
        public virtual ObjectResult<sp_RetornaUsuario_Result> sp_RetornaUsuario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaUsuario_Result>("sp_RetornaUsuario");
        }
    
        public virtual ObjectResult<sp_RetornaUsuarioporID_Result> sp_RetornaUsuarioporID(Nullable<int> id_Usuario)
        {
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("id_Usuario", id_Usuario) :
                new ObjectParameter("id_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaUsuarioporID_Result>("sp_RetornaUsuarioporID", id_UsuarioParameter);
        }
    
        public virtual ObjectResult<RetornaMateriasPorCarreraPorId_Result> RetornaMateriasPorCarreraPorId(Nullable<int> id_Carrera, Nullable<int> id_Materia)
        {
            var id_CarreraParameter = id_Carrera.HasValue ?
                new ObjectParameter("id_Carrera", id_Carrera) :
                new ObjectParameter("id_Carrera", typeof(int));
    
            var id_MateriaParameter = id_Materia.HasValue ?
                new ObjectParameter("id_Materia", id_Materia) :
                new ObjectParameter("id_Materia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaMateriasPorCarreraPorId_Result>("RetornaMateriasPorCarreraPorId", id_CarreraParameter, id_MateriaParameter);
        }
    
        public virtual ObjectResult<sp_RetornaMateriaPorCarreraPorId_Result> sp_RetornaMateriaPorCarreraPorId(Nullable<int> id_Carrera, Nullable<int> id_Materia)
        {
            var id_CarreraParameter = id_Carrera.HasValue ?
                new ObjectParameter("id_Carrera", id_Carrera) :
                new ObjectParameter("id_Carrera", typeof(int));
    
            var id_MateriaParameter = id_Materia.HasValue ?
                new ObjectParameter("id_Materia", id_Materia) :
                new ObjectParameter("id_Materia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaMateriaPorCarreraPorId_Result>("sp_RetornaMateriaPorCarreraPorId", id_CarreraParameter, id_MateriaParameter);
        }
    
        public virtual ObjectResult<sp_RetornaPeriodoporID_Result> sp_RetornaPeriodoporID(Nullable<int> id_Periodo)
        {
            var id_PeriodoParameter = id_Periodo.HasValue ?
                new ObjectParameter("id_Periodo", id_Periodo) :
                new ObjectParameter("id_Periodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaPeriodoporID_Result>("sp_RetornaPeriodoporID", id_PeriodoParameter);
        }
    
        public virtual ObjectResult<sp_RetornaCantonPorProvincia_Result> sp_RetornaCantonPorProvincia(Nullable<int> id_Provincia)
        {
            var id_ProvinciaParameter = id_Provincia.HasValue ?
                new ObjectParameter("id_Provincia", id_Provincia) :
                new ObjectParameter("id_Provincia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaCantonPorProvincia_Result>("sp_RetornaCantonPorProvincia", id_ProvinciaParameter);
        }
    
        public virtual ObjectResult<sp_RetornaDistritoPorCanton_Result> sp_RetornaDistritoPorCanton(Nullable<int> id_Canton)
        {
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("id_Canton", id_Canton) :
                new ObjectParameter("id_Canton", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaDistritoPorCanton_Result>("sp_RetornaDistritoPorCanton", id_CantonParameter);
        }
    
        public virtual ObjectResult<sp_RetornaAlumnoData_Result> sp_RetornaAlumnoData(string pLogin)
        {
            var pLoginParameter = pLogin != null ?
                new ObjectParameter("pLogin", pLogin) :
                new ObjectParameter("pLogin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaAlumnoData_Result>("sp_RetornaAlumnoData", pLoginParameter);
        }
    
        public virtual ObjectResult<sp_ReporteMatriculaGen_Result> sp_ReporteMatriculaGen()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ReporteMatriculaGen_Result>("sp_ReporteMatriculaGen");
        }
    
        public virtual ObjectResult<sp_ReporteMatriculaPorEstudiante_Result> sp_ReporteMatriculaPorEstudiante(string pLogin)
        {
            var pLoginParameter = pLogin != null ?
                new ObjectParameter("pLogin", pLogin) :
                new ObjectParameter("pLogin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ReporteMatriculaPorEstudiante_Result>("sp_ReporteMatriculaPorEstudiante", pLoginParameter);
        }
    }
}
