//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailSenderService
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnvioCorreo
    {
        public int id_Envio { get; set; }
        public string Destinatario { get; set; }
        public string Asunto { get; set; }
        public string Cuerpo { get; set; }
        public string Estado { get; set; }
        public string Bitacora { get; set; }
    }
}
