//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailSenderService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matricula
    {
        public int id_Matricula { get; set; }
        public int id_Materia { get; set; }
        public int id_Alumno { get; set; }
        public int Nota { get; set; }
        public int id_Periodo { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Materia Materia { get; set; }
        public virtual Periodo Periodo { get; set; }
    }
}
